import { getLayout } from "@/components/main-layout";
import PageWrapper from "@/components/page-wrapper";

import {
  ContactHeader,
  Experience,
  FeaturePost,
  FeaturedItem,
  HeaderContent,
  Hero,
  NavHeader,
  Review,
  Services,
} from "@/components/section";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bandage| Tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactHeader>
        <HeaderContent page="home" />
      </ContactHeader>

      <NavHeader />
      <Hero />
      <FeaturedItem />
      <Services />
      <FeaturePost />
      <Review />
      <Experience />
    </>
  );
}

Home.PageWrapper = PageWrapper;
Home.getLayout = getLayout;
